### ISSUE TITLE
`script_path` busted on Mac

### ISSUE THREAD

**Issue by ongardie** [ongardie/cubicle#26]
From <https://doc.rust-lang.org/std/env/fn.current_exe.html#platform-specific-behavior>:
> If the executable was invoked through a symbolic link, some platforms will return the path of the symbolic link and other platforms will return the path of the symbolic link’s target.

Better make this more obvious, more resilient, and configurable.

cc @darrengarvey

**Comment by darrengarvey** [comment]
Great that works. I'm in (a cubicle). 🎉
